spring:
  # Configuração do JPA para ambiente local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuração do datasource Postgres para ambiente local
  datasource:
    url: jdbc:postgresql://localhost:5432/cursos_catalog
    username: cursos_user
    password: cursos_pass
    driver-class-name: org.postgresql.Driver

  # Configuração do Flyway para ambiente local
  flyway:
    url: jdbc:postgresql://localhost:5432/cursos_catalog
    enabled: true
    locations: classpath:db/migration
    user: cursos_user
    password: cursos_pass
    schemas: public

# Configuração do servidor para ambiente local
server:
  port: 8080

# Configuração do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
